 1 name: Unit tests with pytest
 2 on: [push]
 3
 4 jobs:
 5  unit-tests-with-pytest:
 6    runs-on: ubuntu-latest
 7
 8    steps:
 9    - name: Check out repo
10      uses: actions/checkout@v4
11
12    - name: Set up Python
13      uses: actions/setup-python@v5
14      with:
15        python-version: '3.9'
16
17    - name: Install dependencies
18      run: |
19        python -m pip install --upgrade pip
20        pip install pytest
21
22    - name: Test with pytest
23      run: |
24        pytest test_pi.py
